language: node_js
node_js:
  - '8'

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run styleguide:build

deploy:
  # Publish styleguide to GitHub Pages
  - github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: './styleguide/dist'
    provider: pages
    skip_cleanup: true
